# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wd02

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b6ebca0b01db4306b0d9455e89d2cab1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7878b82350774be4a3c85206c7572755 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b6ebca0b01db4306b0d9455e89d2cab1 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wd02'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a9d6d2e1127b486ebb3b0e40cc855e22 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b6ebca0b01db4306b0d9455e89d2cab1 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'